### PR TITLE
Update rowCount to have absolute number

### LINKED ISSUE #23: Last row not rendered when column-count !=  tiles in the row
### Description
Color tile row does not render correctly when row has not the same count as column-count property. 

### Expected outcome

The last row is rendered with the correct number of  tiles 

exptected

### Actual outcome

If you have column-count property set to 5 and 12 items, the last 2 items does not show.
It happens to 11 to 14 items. The last row to show MUST have a number of items equal to the colomn-count.
picker

### Steps to reproduce

``` 
<paper-swatch-picker column-count="5" color-list='["#65a5f2", "#2b63ba", "#83be54", "#3b8638", "#f0d551", "#d7be48","#65a5f2", "#2b63ba", "#83be54", "#3b8638", "#f0d551", "#d7be48"]'></paper-swatch-picker>
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [not tested] Safari 9
- [not tested] Safari 8
- [not tested] Safari 7
- [not tested] Edge
- [not tested] IE 11
- [not tested] IE 10

### PR DESCRIPTION
**Pull request by jean-maxime**
This would fix #23 
Add absolute to have always the good height for the `paper-listbox`

### CODE REVIEW

**Comment by jean-maxime** [comment]
I signed it!

**Comment by notwaldorf** [comment]
The tests seem to be failing; I don't think it's your fault, but I think the solution is to add the polyfill to the `basic.html` test file, like it's done here: https://github.com/PolymerElements/paper-tooltip/blob/master/test/basic.html#L23. Would you mind giving that a try, please?

**Comment by jean-maxime** [comment]
The polyfill is already added : https://github.com/PolymerElements/paper-swatch-picker/blob/master/test/basic.html#L22
To make it work, I have to import manually `neon-animation/web-animations.html` in `basic.html` but I don't think it's the best solution ?

**Comment by jean-maxime** [comment]
Nice, it works now, thank you for the help ;)

**Comment by notwaldorf** [comment]
Thanks!

**Pull request merged**
