### PR TITLE
Colors and columns can now be dynamically updated.

### PR DESCRIPTION
**Pull request by microDimensions**
Default colors can be retrieved from outside.

### CODE REVIEW

**Comment by feuerste** [comment]
@notwaldorf, what do you think about this PR? Could it be merged?

**Comment by feuerste** [comment]
@notwaldorf, I think this PR would greatly improve the usability when changing colors and columns. Can you please double-check it? Thanks a lot!

**Comment by notwaldorf** [comment]
This PR is great, but can you add a test that the colors and columns are, in fact updateable?

**Comment by feuerste** [comment]
I just added a test, can you please check again?

**Comment by feuerste** [comment]
@notwaldorf, I added a test, can you please check again? Thank you!

**Comment by notwaldorf** [comment]
Thanks!

**Comment by feuerste** [comment]
Thanks a lot for merging! Would you mind releasing a new version, too?

**Pull request merged**
