### PR TITLE
Added custom icon property

### PR DESCRIPTION
**Pull request by KeithHenry**
It should be possible to use an alternate icon, for instance if using two controls to set fore and back colour.

### CODE REVIEW

**Comment by jsilvermist** [comment]
Duplicate of #20.

**Comment by KeithHenry** [comment]
@jsilvermist ah, sorry, didn't spot that.

I think we might need to go further though, as it might be better to expose the `dropdown-trigger` slot from the `paper-menu-button`, as that would allow more control over the appearance of that button.

**Comment by jsilvermist** [comment]
@KeithHenry I tried playing around with it to add an extensible slot for the `dropdown-trigger`, and this is what I came up with. It's a little messy, but I'm not really sure how to clean it up and leave it fully extendable.

https://github.com/jsilvermist/paper-swatch-picker/commit/0d5d1608c5d6a718e2e4953e4cc0802d955057b0

(Based on `icon-binding` branch)

**Comment by KeithHenry** [comment]
The messy bit appears to be assumptions required to set the button colour on change, but that isn't needed in all contexts. For instance it's nice if this control sets a font colour and further typing will be the same as the button, but if it sets a block back colour that's a one time action - it either shouldn't change with the swatch selection, or it should also change to match the cursor/caret selection's current colour.

I think that maybe this should be two controls - the swatches (a control that builds the grid of colours) and the wrapper that makes it into a drop down menu button

**Pull request closed without merging**
