### PR TITLE
Change double quotes to single quotes for more consistency

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by notwaldorf** [comment]
This is done on purpose. Since that array needs to be parsed as JSON, the strings need to use double quotes. If you flip them to single quotes and run this locally, you will get a warning in the console.

**Comment by abdonrd** [comment]
@notwaldorf I haven't any problem. :confused: 

screen shot 2016-03-21 at 18 55 33

**Comment by notwaldorf** [comment]
@abdonrd I meant in the `<paper-swatch-picker column-count=5 color-list="['#65a5f2', '#83be54', '#f0d551', '#e5943c', '#a96ddb']"></paper-swatch-picker>` case that you also updated.

**Comment by abdonrd** [comment]
@notwaldorf got it! There you are totally right, sorry!

Maybe we can update only the javascript code, right?

**Comment by notwaldorf** [comment]
Yup, the JS changes would be ok. Feel free to re-open this PR with the updated changes!

**Comment by abdonrd** [comment]
Done! :sparkles: https://github.com/PolymerElements/paper-swatch-picker/pull/7

**Pull request closed without merging**
